version: "3"

services:
  redis:
    image: redis

  api_user:
    build: ./api_user
    links:
      - redis
    ports:
      - "3001"
    environment:
      PORT_NUMBER: 3001

  api_customer:
    build: ./api_customer
    links:
      - redis
    ports:
      - "3002"
    environment:
      PORT_NUMBER: 3002

  nginx:
    build: ./nginx
    links:
      - api_customer
      - api_user
    ports:
      - "8080:8080"
